# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Builds code
      run: npm run build:ci:prod
    - name: deploy to github pages
      run: |
            git fetch
            git checkout github-pages
            cp -R ./dist/apps/dynamic-forms/. ../docs
            rm -rf ./**
            cp -R ../docs ./docs
            git config user.name "Github Actions"
            git config user.email "actions@github.com"
            git add ./
            git commit -m "CI Build" --allow-empty
            git push
      
